"""Device profiles (``fpga_device``): package pins and resource classes.

Bundled profiles are generated by ``scripts/extract_device_profiles.py``
from the open device databases in the pinned OSS CAD Suite. A project can
add its own ``<id>.fpga-device.json`` next to the contract.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

Family = Literal["ice40", "ecp5", "gowin"]
ResourceClass = Literal["logic", "ram", "dsp", "io", "clock", "pll", "other"]
BUNDLED = Path(__file__).resolve().parent / "devices"


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")


class DevicePin(_Strict):
    name: str
    bank: int | None = None
    functions: list[str] = Field(default_factory=list[str])
    caution: Literal["config", "jtag"] | None = None
    clock: bool = False


class DeviceProfile(_Strict):
    schema_version: Literal[1] = 1
    system: Literal["fpga"] = "fpga"
    artifact_kind: Literal["fpga_device"] = "fpga_device"
    id: str = Field(pattern=r"^[a-z0-9][a-z0-9-]*$")
    vendor: str
    family: Family
    part: str
    package: str
    speed: str | None = None
    boards: list[str] = Field(default_factory=list[str])
    source: str
    nextpnr_args: list[str]
    pack_args: list[str]
    io_voltage_max_v: float = Field(gt=0)
    io_standards: list[str]
    resources: dict[str, ResourceClass]
    pins: list[DevicePin] = Field(min_length=1)

    def pin(self, name: str) -> DevicePin | None:
        return next((p for p in self.pins if p.name == name), None)


def bundled_ids() -> list[str]:
    return sorted(path.stem for path in BUNDLED.glob("*.json"))


def load_profile(profile_id: str, search_dirs: list[Path] | None = None) -> DeviceProfile:
    for directory in search_dirs or []:
        candidate = directory / f"{profile_id}.fpga-device.json"
        if candidate.is_file():
            return DeviceProfile.model_validate(json.loads(candidate.read_text(encoding="utf-8")))
    path = BUNDLED / f"{profile_id}.json"
    if not path.is_file():
        raise ValueError(
            f"unknown device profile {profile_id} (bundled: {', '.join(bundled_ids())})"
        )
    return DeviceProfile.model_validate(json.loads(path.read_text(encoding="utf-8")))
