"""Deterministic projections of the contract: the family constraint file
(PCF, LPF or CST) and the pin map export."""

from __future__ import annotations

from pathlib import Path

from .contract import FpgaContract, Pin
from .devices import DeviceProfile
from .interchange import FpgaPinmap, PinmapEntry

CONSTRAINT_SUFFIX = {"ice40": ".pcf", "ecp5": ".lpf", "gowin": ".cst"}


def _header(contract: FpgaContract, comment: str) -> list[str]:
    return [
        f"{comment} Generated by fpga-agent from {contract.name}.fpga.json; do not edit.",
        f"{comment} Regenerate with `fpga constraints <contract>`.",
    ]


def _pcf(contract: FpgaContract) -> list[str]:
    lines = _header(contract, "#")
    for pin in contract.pins:
        pull = " -pullup yes" if pin.pull == "up" else ""
        lines.append(f"set_io -nowarn{pull} {pin.port} {pin.package_pin}")
    lines += [f"set_frequency {c.port} {c.frequency_mhz:g}" for c in contract.clocks]
    return lines


def _lpf_iobuf(pin: Pin) -> str | None:
    attrs: list[str] = []
    if pin.io_standard:
        attrs.append(f"IO_TYPE={pin.io_standard}")
    if pin.pull:
        attrs.append(f"PULLMODE={pin.pull.upper()}")
    return f'IOBUF PORT "{pin.port}" {" ".join(attrs)};' if attrs else None


def _lpf(contract: FpgaContract) -> list[str]:
    lines = _header(contract, "#")
    for pin in contract.pins:
        lines.append(f'LOCATE COMP "{pin.port}" SITE "{pin.package_pin}";')
        iobuf = _lpf_iobuf(pin)
        if iobuf:
            lines.append(iobuf)
    lines += [f'FREQUENCY PORT "{c.port}" {c.frequency_mhz:g} MHZ;' for c in contract.clocks]
    return lines


def _cst(contract: FpgaContract) -> list[str]:
    lines = _header(contract, "//")
    for pin in contract.pins:
        lines.append(f'IO_LOC "{pin.port}" {pin.package_pin};')
        attrs: list[str] = []
        if pin.io_standard:
            attrs.append(f"IO_TYPE={pin.io_standard}")
        if pin.pull:
            attrs.append(f"PULL_MODE={pin.pull.upper()}")
        if attrs:
            lines.append(f'IO_PORT "{pin.port}" {" ".join(attrs)};')
    return lines


def constraints_text(contract: FpgaContract, profile: DeviceProfile) -> str:
    render = {"ice40": _pcf, "ecp5": _lpf, "gowin": _cst}[profile.family]
    return "\n".join(render(contract)) + "\n"


def pinmap_export(
    contract: FpgaContract,
    profile: DeviceProfile,
    contract_sha256: str,
    circuit_sha256: str | None = None,
) -> FpgaPinmap:
    used = {p.package_pin for p in contract.pins}
    return FpgaPinmap(
        design=contract.name,
        contract_sha256=contract_sha256,
        circuit_sha256=circuit_sha256,
        device_ref=contract.device.ref,
        device_profile=profile.id,
        part=profile.part,
        package=profile.package,
        io_voltage_max_v=profile.io_voltage_max_v,
        pins=[
            PinmapEntry(
                port=p.port,
                package_pin=p.package_pin,
                net=p.net,
                io_standard=p.io_standard,
                pull=p.pull,
            )
            for p in contract.pins
        ],
        free_pins=[p.name for p in profile.pins if p.name not in used and p.caution is None],
    )


def pinmap_markdown(pinmap: FpgaPinmap) -> str:
    lines = [
        f"# FPGA pin map: {pinmap.design}",
        "",
        f"- device: {pinmap.device_ref} = {pinmap.part} ({pinmap.package}, "
        f"profile {pinmap.device_profile})",
        f"- contract sha256: `{pinmap.contract_sha256}`",
        "",
        "| Port | Package pin | Net | I/O standard | Pull |",
        "| --- | --- | --- | --- | --- |",
    ]
    for p in pinmap.pins:
        lines.append(
            f"| {p.port} | {p.package_pin} | {p.net or ''} | {p.io_standard or ''} | "
            f"{p.pull or ''} |"
        )
    lines += ["", f"Free user I/O pins: {', '.join(pinmap.free_pins) or 'none'}"]
    return "\n".join(lines) + "\n"


def write_text(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
