"""Register map projections: the ``fpga_regmap`` export for firmware-agent
and the HDL constants file the RTL uses, both from ``contract.registers``.

The ``fpga.regmap`` gate fails when the HDL constants file is missing,
stale, or not used by any design source, so a register the firmware header
names always exists at the same address in the HDL.
"""

from __future__ import annotations

import re
from pathlib import Path

from .contract import FpgaContract, RegisterMap, resolve
from .interchange import FpgaRegmap, RegmapField, RegmapRegister


def _registers(contract: FpgaContract) -> RegisterMap:
    if contract.registers is None:
        raise ValueError("contract declares no registers")
    return contract.registers


def regmap_export(contract: FpgaContract, contract_sha256: str) -> FpgaRegmap:
    regs = _registers(contract)
    return FpgaRegmap(
        design=contract.name,
        contract_sha256=contract_sha256,
        device_ref=contract.device.ref,
        bus=regs.bus,
        i2c_address=regs.i2c_address,
        data_width=regs.data_width,
        address_width=regs.address_width,
        registers=[
            RegmapRegister(
                name=r.name,
                offset=r.offset,
                access=r.access,
                reset=r.reset,
                description=r.description,
                fields=[
                    RegmapField(
                        name=f.name,
                        lsb=f.lsb,
                        width=f.width,
                        mask=((1 << f.width) - 1) << f.lsb,
                        access=f.access or r.access,
                        description=f.description,
                    )
                    for f in r.fields
                ],
            )
            for r in sorted(regs.registers, key=lambda r: r.offset)
        ],
    )


def package_name(contract: FpgaContract) -> str:
    """VHDL package / Verilog macro prefix: the contract name as an identifier."""
    ident = re.sub(r"_+", "_", re.sub(r"[^a-z0-9]", "_", contract.name.lower())).strip("_")
    if not ident or not ident[0].isalpha():
        ident = f"d_{ident}"
    return f"{ident}_regs"


def _hex(value: int, bits: int) -> str:
    return f"{value:0{(bits + 3) // 4}x}"


def _vhdl(contract: FpgaContract, regs: RegisterMap) -> list[str]:
    pkg = f"{package_name(contract)}_pkg"
    dw, aw = regs.data_width, regs.address_width
    lines = [
        f"-- Generated by fpga-agent from {contract.name}.fpga.json registers; do not edit.",
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "",
        f"package {pkg} is",
        f"  constant REGMAP_DATA_WIDTH : natural := {dw};",
        f"  constant REGMAP_ADDR_WIDTH : natural := {aw};",
    ]
    if regs.i2c_address is not None:
        lines.append(f"  constant REGMAP_I2C_ADDRESS : natural := 16#{regs.i2c_address:02x}#;")
    for reg in sorted(regs.registers, key=lambda r: r.offset):
        name = f"REG_{reg.name.upper()}"
        lines.append(f"  -- {reg.name}: {reg.access}")
        lines.append(f"  constant {name}_ADDR : natural := {reg.offset};")
        lines.append(
            f"  constant {name}_RESET : std_logic_vector({dw - 1} downto 0) := "
            f'x"{_hex(reg.reset, dw)}";'
        )
        for fld in reg.fields:
            lines.append(f"  constant {name}_{fld.name.upper()}_LSB : natural := {fld.lsb};")
            lines.append(f"  constant {name}_{fld.name.upper()}_WIDTH : natural := {fld.width};")
    lines += [f"end package {pkg};", ""]
    return lines


def _verilog(contract: FpgaContract, regs: RegisterMap) -> list[str]:
    prefix = package_name(contract).upper()
    dw, aw = regs.data_width, regs.address_width
    lines = [
        f"// Generated by fpga-agent from {contract.name}.fpga.json registers; do not edit.",
        f"`ifndef {prefix}_VH",
        f"`define {prefix}_VH",
        f"`define {prefix}_DATA_WIDTH {dw}",
        f"`define {prefix}_ADDR_WIDTH {aw}",
    ]
    if regs.i2c_address is not None:
        lines.append(f"`define {prefix}_I2C_ADDRESS 7'h{regs.i2c_address:02x}")
    for reg in sorted(regs.registers, key=lambda r: r.offset):
        name = f"{prefix}_{reg.name.upper()}"
        lines.append(f"// {reg.name}: {reg.access}")
        lines.append(f"`define {name}_ADDR {aw}'h{_hex(reg.offset, aw)}")
        lines.append(f"`define {name}_RESET {dw}'h{_hex(reg.reset, dw)}")
        for fld in reg.fields:
            lines.append(f"`define {name}_{fld.name.upper()}_LSB {fld.lsb}")
            lines.append(f"`define {name}_{fld.name.upper()}_WIDTH {fld.width}")
    lines += ["`endif", ""]
    return lines


def hdl_package_text(contract: FpgaContract) -> str:
    regs = _registers(contract)
    if contract.design_language == "vhdl":
        return "\n".join(_vhdl(contract, regs))
    return "\n".join(_verilog(contract, regs))


def regmap_problems(contract: FpgaContract, contract_path: Path) -> list[str]:
    """Why the HDL is not bound to the register map; empty when it is."""
    regs = _registers(contract)
    package = resolve(contract_path, regs.hdl_package)
    if not package.is_file():
        return [f"{regs.hdl_package} missing; run `fpga regmap`"]
    if package.read_text(encoding="utf-8") != hdl_package_text(contract):
        return [f"{regs.hdl_package} stale; regenerate with `fpga regmap`"]
    if contract.design_language == "vhdl":
        use = re.compile(rf"\buse\s+work\.{package_name(contract)}_pkg\.", re.IGNORECASE)
    else:
        use = re.compile(rf'`include\s+"(?:[^"]*/)?{re.escape(Path(regs.hdl_package).name)}"')
    for source in contract.sources:
        if source.path == regs.hdl_package:
            continue
        path = resolve(contract_path, source.path)
        if path.is_file() and use.search(path.read_text(encoding="utf-8")):
            return []
    return [f"no design source uses {regs.hdl_package}; the RTL is not bound to the register map"]
